apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
spec:
  source:
    git:
      url: https://github.com/vchrisb/spring-petclinic
      ref:
        branch: tap
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"